export interface Emoji {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  name: string;
  emojis: string[];
}

// A highly curated, lean list of common emojis and keywords
export const EMOJI_DATABASE: Emoji[] = [
  // Smileys
  { char: '😀', keywords: ['smile', 'happy', 'grin'] },
  { char: '😃', keywords: ['smile', 'happy', 'big'] },
  { char: '😄', keywords: ['smile', 'happy', 'laugh'] },
  { char: '😁', keywords: ['smile', 'happy', 'beaming'] },
  { char: '😆', keywords: ['laugh', 'squinting'] },
  { char: '😅', keywords: ['sweat', 'smile', 'nervous'] },
  { char: '😂', keywords: ['laugh', 'tears', 'joy', 'lol'] },
  { char: '🤣', keywords: ['rofl', 'rolling', 'laugh'] },
  { char: '😊', keywords: ['smile', 'blush'] },
  { char: '😇', keywords: ['angel', 'halo'] },
  { char: '🥰', keywords: ['love', 'hearts', 'affection'] },
  { char: '😍', keywords: ['love', 'heart', 'eyes'] },
  { char: '🤩', keywords: ['star', 'eyes', 'wow'] },
  { char: '😘', keywords: ['kiss', 'heart'] },
  { char: '😋', keywords: ['yum', 'delicious'] },
  { char: '😛', keywords: ['tongue', 'out'] },
  { char: '😜', keywords: ['wink', 'tongue', 'joke'] },
  { char: '🤪', keywords: ['crazy', 'zany'] },
  { char: '😝', keywords: ['squinting', 'tongue'] },
  { char: '🤑', keywords: ['money', 'mouth', 'rich'] },
  { char: '🤗', keywords: ['hug', 'hugging'] },
  { char: '🤭', keywords: ['hand', 'mouth', 'giggle'] },
  { char: '🤫', keywords: ['shh', 'quiet'] },
  { char: '🤔', keywords: ['think', 'thinking', 'hmm'] },
  { char: '🤐', keywords: ['zipper', 'mouth', 'secret'] },
  { char: '🤨', keywords: ['raised', 'eyebrow', 'sus'] },
  { char: '😐', keywords: ['neutral', 'face'] },
  { char: '😑', keywords: ['expressionless'] },
  { char: '😶', keywords: ['no', 'mouth', 'speechless'] },
  { char: '😏', keywords: ['smirk', 'flirt'] },
  { char: '😒', keywords: ['unamused', 'annoyed'] },
  { char: '🙄', keywords: ['roll', 'eyes', 'annoyed'] },
  { char: '😬', keywords: ['grimace', 'awkward', 'yikes'] },
  { char: '🤥', keywords: ['lying', 'pinocchio'] },
  { char: '😌', keywords: ['relieved', 'phew'] },
  { char: '😔', keywords: ['pensive', 'sad'] },
  { char: '😪', keywords: ['sleepy', 'tired'] },
  { char: '🤤', keywords: ['drooling', 'yummy'] },
  { char: '😴', keywords: ['sleeping', 'zzz'] },
  { char: '😷', keywords: ['mask', 'sick'] },
  { char: '🤒', keywords: ['thermometer', 'sick'] },
  { char: '🤕', keywords: ['bandage', 'hurt'] },
  { char: '🤢', keywords: ['nauseated', 'sick', 'gross'] },
  { char: '🤮', keywords: ['vomiting', 'puke', 'sick'] },
  { char: '🤧', keywords: ['sneezing', 'sick'] },
  { char: '🥵', keywords: ['hot', 'sweat'] },
  { char: '🥶', keywords: ['cold', 'freezing'] },
  { char: '🥴', keywords: ['woozy', 'drunk'] },
  { char: '😵', keywords: ['dizzy', 'dead'] },
  { char: '🤯', keywords: ['exploding', 'mind', 'blown'] },
  { char: '🤠', keywords: ['cowboy', 'hat'] },
  { char: '🥳', keywords: ['partying', 'celebrate', 'party'] },
  { char: '😎', keywords: ['cool', 'sunglasses'] },
  { char: '🤓', keywords: ['nerd', 'glasses'] },
  { char: '🧐', keywords: ['monocle', 'fancy'] },
  { char: '😕', keywords: ['confused', 'sad'] },
  { char: '😟', keywords: ['worried', 'sad'] },
  { char: '🙁', keywords: ['slightly', 'frowning'] },
  { char: '☹️', keywords: ['frowning', 'sad'] },
  { char: '😮', keywords: ['open', 'mouth', 'surprise'] },
  { char: '😯', keywords: ['hushed', 'surprise'] },
  { char: '😲', keywords: ['astonished', 'wow'] },
  { char: '😳', keywords: ['flushed', 'blush', 'embarrassed'] },
  { char: '🥺', keywords: ['pleading', 'puppy', 'eyes'] },
  { char: '😦', keywords: ['frowning', 'open'] },
  { char: '😧', keywords: ['anguished', 'sad'] },
  { char: '😨', keywords: ['fearful', 'scared'] },
  { char: '😰', keywords: ['anxious', 'sweat', 'scared'] },
  { char: '😥', keywords: ['sad', 'relieved'] },
  { char: '😢', keywords: ['crying', 'tear', 'sad'] },
  { char: '😭', keywords: ['loudly', 'crying', 'sob', 'sad'] },
  { char: '😱', keywords: ['screaming', 'fear', 'scared'] },
  { char: '😖', keywords: ['confounded'] },
  { char: '😣', keywords: ['persevering'] },
  { char: '😞', keywords: ['disappointed', 'sad'] },
  { char: '😓', keywords: ['downcast', 'sweat'] },
  { char: '😩', keywords: ['weary', 'tired'] },
  { char: '😫', keywords: ['tired'] },
  { char: '🥱', keywords: ['yawning', 'tired'] },
  { char: '😤', keywords: ['triumph', 'angry'] },
  { char: '😡', keywords: ['pouting', 'angry', 'mad'] },
  { char: '😠', keywords: ['angry', 'mad'] },
  { char: '🤬', keywords: ['cursing', 'angry', 'mad'] },
  { char: '😈', keywords: ['smiling', 'horns', 'devil'] },
  { char: '👿', keywords: ['angry', 'horns', 'devil'] },
  { char: '💀', keywords: ['skull', 'dead', 'deadass'] },
  { char: '☠️', keywords: ['skull', 'crossbones', 'danger'] },
  { char: '💩', keywords: ['poop', 'shit', 'crap'] },
  { char: '🤡', keywords: ['clown', 'fool'] },
  { char: '👹', keywords: ['ogre', 'monster'] },
  { char: '👺', keywords: ['goblin', 'monster'] },
  { char: '👻', keywords: ['ghost', 'boo'] },
  { char: '👽', keywords: ['alien', 'ufo'] },
  { char: '👾', keywords: ['alien', 'monster', 'game'] },
  { char: '🤖', keywords: ['robot', 'bot'] },

  // Gestures
  { char: '👋', keywords: ['wave', 'hand', 'hello', 'hi', 'bye'] },
  { char: '🤚', keywords: ['raised', 'back', 'hand'] },
  { char: '🖐️', keywords: ['hand', 'fingers', 'splayed'] },
  { char: '✋', keywords: ['raised', 'hand', 'stop'] },
  { char: '🖖', keywords: ['vulcan', 'salute', 'spock'] },
  { char: '👌', keywords: ['ok', 'hand', 'perfect'] },
  { char: '🤌', keywords: ['pinched', 'fingers', 'italian'] },
  { char: '🤏', keywords: ['pinching', 'hand', 'small'] },
  { char: '✌️', keywords: ['victory', 'hand', 'peace'] },
  { char: '🤞', keywords: ['crossed', 'fingers', 'luck'] },
  { char: '🤟', keywords: ['love', 'you', 'gesture'] },
  { char: '🤘', keywords: ['sign', 'horns', 'rock'] },
  { char: '🤙', keywords: ['call', 'me', 'hand', 'shaka'] },
  { char: '👈', keywords: ['point', 'left'] },
  { char: '👉', keywords: ['point', 'right'] },
  { char: '👆', keywords: ['point', 'up'] },
  { char: '🖕', keywords: ['middle', 'finger'] },
  { char: '👇', keywords: ['point', 'down'] },
  { char: '☝️', keywords: ['index', 'pointing', 'up'] },
  { char: '👍', keywords: ['thumbs', 'up', 'yes', 'good'] },
  { char: '👎', keywords: ['thumbs', 'down', 'no', 'bad'] },
  { char: '✊', keywords: ['raised', 'fist', 'power'] },
  { char: '👊', keywords: ['oncoming', 'fist', 'punch', 'brofist'] },
  { char: '🤛', keywords: ['left', 'fist'] },
  { char: '🤜', keywords: ['right', 'fist'] },
  { char: '👏', keywords: ['clapping', 'hands', 'applause'] },
  { char: '🙌', keywords: ['raising', 'hands', 'praise'] },
  { char: '👐', keywords: ['open', 'hands', 'hug'] },
  { char: '🤲', keywords: ['palms', 'up', 'together'] },
  { char: '🤝', keywords: ['handshake', 'deal'] },
  { char: '🙏', keywords: ['folded', 'hands', 'please', 'pray', 'thanks'] },
  { char: '✍️', keywords: ['writing', 'hand'] },
  { char: '💅', keywords: ['nail', 'polish', 'sass'] },
  { char: '🤳', keywords: ['selfie'] },
  { char: '💪', keywords: ['flexed', 'biceps', 'strong', 'muscle'] },

  // Symbols & Other popular ones
  { char: '❤️', keywords: ['red', 'heart', 'love'] },
  { char: '🧡', keywords: ['orange', 'heart'] },
  { char: '💛', keywords: ['yellow', 'heart'] },
  { char: '💚', keywords: ['green', 'heart'] },
  { char: '💙', keywords: ['blue', 'heart'] },
  { char: '💜', keywords: ['purple', 'heart'] },
  { char: '🖤', keywords: ['black', 'heart'] },
  { char: '🤍', keywords: ['white', 'heart'] },
  { char: '🤎', keywords: ['brown', 'heart'] },
  { char: '💔', keywords: ['broken', 'heart', 'sad'] },
  { char: '❤️‍🔥', keywords: ['heart', 'fire', 'passion'] },
  { char: '❤️‍🩹', keywords: ['mending', 'heart', 'healing'] },
  { char: '💕', keywords: ['two', 'hearts'] },
  { char: '💞', keywords: ['revolving', 'hearts'] },
  { char: '💓', keywords: ['beating', 'heart'] },
  { char: '💗', keywords: ['growing', 'heart'] },
  { char: '💖', keywords: ['sparkling', 'heart'] },
  { char: '💘', keywords: ['heart', 'arrow', 'cupid'] },
  { char: '💝', keywords: ['heart', 'ribbon', 'gift'] },
  { char: '🔥', keywords: ['fire', 'hot', 'lit'] },
  { char: '✨', keywords: ['sparkles', 'magic', 'shiny'] },
  { char: '🌟', keywords: ['glowing', 'star', 'awesome'] },
  { char: '💫', keywords: ['dizzy', 'star'] },
  { char: '💯', keywords: ['hundred', 'points', 'perfect'] },
  { char: '💢', keywords: ['anger', 'symbol'] },
  { char: '💬', keywords: ['speech', 'balloon', 'chat'] },
  { char: '👁️', keywords: ['eye'] },
  { char: '👀', keywords: ['eyes', 'look', 'sus'] },
  { char: '🧠', keywords: ['brain', 'smart'] },
  { char: '🗣️', keywords: ['speaking', 'head'] },
  { char: '💦', keywords: ['sweat', 'drops', 'water'] },
  { char: '💨', keywords: ['dashing', 'away', 'wind'] },
  { char: '🚀', keywords: ['rocket', 'ship', 'launch', 'moon'] },
  { char: '💡', keywords: ['light', 'bulb', 'idea'] },
  { char: '❌', keywords: ['cross', 'mark', 'no', 'wrong'] },
  { char: '✅', keywords: ['check', 'mark', 'yes', 'done'] },
  { char: '⚠️', keywords: ['warning', 'sign', 'alert'] },
  { char: '🍆', keywords: ['eggplant', 'aubergine'] },
  { char: '🍑', keywords: ['peach', 'butt'] },
  { char: '🍕', keywords: ['pizza', 'food'] },
  { char: '🍔', keywords: ['hamburger', 'food'] },
  { char: '🍟', keywords: ['french', 'fries'] },
  { char: '🌭', keywords: ['hot', 'dog'] },
  { char: '🍿', keywords: ['popcorn', 'movie'] },
  { char: '🍺', keywords: ['beer', 'mug', 'drink'] },
  { char: '🍻', keywords: ['clinking', 'beer', 'mugs', 'cheers'] },
  { char: '🥂', keywords: ['clinking', 'glasses', 'cheers'] },
  { char: '🎉', keywords: ['party', 'popper', 'celebration'] },
  { char: '🎊', keywords: ['confetti', 'ball', 'celebration'] },
  { char: '🎈', keywords: ['balloon', 'party'] },
  { char: '🎂', keywords: ['birthday', 'cake'] },
];

// The default categories to display when not searching
export const CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    emojis: ['😀', '😂', '😊', '😇', '🥰', '😍', '😜', '😎', '🤔', '😴', '😭', '😱'],
  },
  {
    name: 'Gestures',
    emojis: ['👍', '👎', '👊', '✌️', '👋', '👏', '🙌', '🤝', '🙏', '💪', '🔥', '🎉'],
  },
  {
    name: 'Symbols',
    emojis: ['❤️', '🍆', '🌟', '💯', '👀', '💬', '🚀', '💡', '❌', '✅', '⚠️', '💀'],
  },
];

export function searchEmojis(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  
  // Filter emojis that match any keyword or char
  const results = EMOJI_DATABASE.filter(
    (e) => e.char.includes(q) || e.keywords.some((kw) => kw.includes(q))
  );
  
  // Return just the characters, capped to prevent massive DOM if we had more emojis
  return results.map((e) => e.char).slice(0, 100);
}
